// Signaling transport selection.
//
// Two interchangeable transports carry the WebRTC handshake:
//
//   local    - websocket to the picklecast server that served this page
//              (see server.py).  Works with no internet connection.
//   trackers - public WebTorrent trackers via p2pt.  Works with no server.
//
// A page tries the local server first with a very short timeout, since the
// usual deployment is Github Pages where nothing is listening.  Both
// transports expose the small slice of the p2pt API that webrtc.js uses:
// on(), send(), start(), destroy().

var TRACKERS = [
    'wss://tracker.openwebtorrent.com',
    'wss://tracker.webtorrent.dev',
    'wss://tracker.btorrent.xyz',
    'wss://tracker.files.fm:7073/announce'
];

// config.js is a stub on Github Pages and generated by server.py locally
var CONFIG = window.PICKLECAST_CONFIG || {};

// How long to wait for the local server before falling back to trackers.  On
// Github Pages nothing is listening, so the probe has to be cheap; when the
// page came from the server itself it is worth waiting out a slow display
// machine rather than bouncing to the trackers.
var PROBE_TIMEOUT = CONFIG.probeTimeout || (CONFIG.local ? 5000 : 400);

function localSignalURL(identifier) {
    var loc = window.location;
    var proto = loc.protocol === 'https:' ? 'wss:' : 'ws:';
    // strip the filename, keeping any subdirectory the page is served from
    var dir = loc.pathname.replace(/[^/]*$/, '');
    return proto + '//' + loc.host + dir + 'ws?room=' + encodeURIComponent(identifier);
}

// Minimal event emitter shared by both transports
function Emitter() {
    this.handlers = {};
}

Emitter.prototype.on = function(event, fn) {
    (this.handlers[event] = this.handlers[event] || []).push(fn);
    return this;
};

Emitter.prototype.emit = function(event) {
    var args = Array.prototype.slice.call(arguments, 1);
    (this.handlers[event] || []).forEach(function(fn) {
        try { fn.apply(null, args); } catch (e) { console.error(e); }
    });
};

// --- local server transport ---

function LocalSignal(identifier, ws) {
    Emitter.call(this);
    this.identifier = identifier;
    this.ws = ws;
    this.peers = {};
    this.destroyed = false;
}

LocalSignal.prototype = Object.create(Emitter.prototype);

LocalSignal.prototype.start = function() {
    var self = this;

    this.ws.onmessage = function(event) {
        var data;
        try { data = JSON.parse(event.data); } catch (e) { return; }

        if (data.type === 'welcome') {
            // let the page show the LAN address clients should open
            window.dispatchEvent(new CustomEvent('picklecast-serverinfo', {
                detail: {address: data.address, version: data.version}
            }));
            self.emit('trackerconnect');
            // peers already in the room when we joined
            (data.peers || []).forEach(function(id) {
                self.emit('peerconnect', self.peer(id));
            });
        } else if (data.type === 'peerconnect') {
            self.emit('peerconnect', self.peer(data.id));
        } else if (data.type === 'peerclose') {
            var peer = self.peers[data.id];
            delete self.peers[data.id];
            if (peer) self.emit('peerclose', peer);
        } else if (data.type === 'msg') {
            self.emit('msg', self.peer(data.from), data.msg);
        }
    };

    this.ws.onclose = function() {
        if (self.destroyed) return;
        // treat a dropped server connection as every peer going away
        Object.keys(self.peers).forEach(function(id) {
            var peer = self.peers[id];
            delete self.peers[id];
            self.emit('peerclose', peer);
        });
        setTimeout(function() { self.reconnect(); }, 2000);
    };
};

LocalSignal.prototype.reconnect = function() {
    if (this.destroyed) return;
    var self = this;
    var ws = new WebSocket(localSignalURL(this.identifier));
    ws.onopen = function() {
        self.ws = ws;
        self.start();
    };
    ws.onerror = function() {
        if (!self.destroyed) setTimeout(function() { self.reconnect(); }, 2000);
    };
};

LocalSignal.prototype.peer = function(id) {
    if (!this.peers[id]) this.peers[id] = {id: id, local: true};
    return this.peers[id];
};

LocalSignal.prototype.send = function(peer, msg) {
    if (this.ws.readyState !== WebSocket.OPEN)
        return Promise.reject(new Error('signaling server disconnected'));
    this.ws.send(JSON.stringify({type: 'msg', to: peer.id, msg: msg}));
    return Promise.resolve();
};

LocalSignal.prototype.destroy = function() {
    this.destroyed = true;
    try { this.ws.close(); } catch (e) {}
};

// --- transport selection ---

// Wraps the transport that is eventually chosen.  Returned synchronously so
// callers can register handlers and call start() before the probe finishes.
function Transport(identifier) {
    Emitter.call(this);
    this.identifier = identifier;
    this.inner = null;
    this.queue = [];
    this.destroyed = false;
}

Transport.prototype = Object.create(Emitter.prototype);

Transport.prototype.adopt = function(inner) {
    var self = this;
    this.inner = inner;
    ['msg', 'peerconnect', 'peerclose', 'trackerconnect'].forEach(function(event) {
        inner.on(event, function() {
            var args = [event].concat(Array.prototype.slice.call(arguments));
            self.emit.apply(self, args);
        });
    });
    inner.start();
    // flush anything sent before the transport was ready
    var queued = this.queue;
    this.queue = [];
    queued.forEach(function(item) {
        inner.send(item.peer, item.msg).then(item.resolve, item.reject);
    });
};

Transport.prototype.start = function() {
    var self = this;

    var settled = false;
    var ws;
    var timer;

    function useTrackers(reason) {
        if (settled || self.destroyed) return;
        settled = true;
        clearTimeout(timer);
        if (ws) { ws.onopen = ws.onerror = ws.onclose = null; try { ws.close(); } catch (e) {} }
        if (CONFIG.localOnly) {
            console.warn('local signaling unavailable and trackers disabled:', reason);
            self.emit('error', reason);
            // keep retrying the local server rather than leaking to the internet
            var local = new LocalSignal(self.identifier, {
                readyState: WebSocket.CLOSED, close: function() {}
            });
            self.adopt(local);
            local.reconnect();
            return;
        }
        console.log('using public trackers (' + reason + ')');
        self.adopt(new P2PT(TRACKERS, self.identifier));
    }

    // probe the server that served this page
    try {
        ws = new WebSocket(localSignalURL(this.identifier));
    } catch (e) {
        useTrackers('websocket unavailable');
        return;
    }

    timer = setTimeout(function() { useTrackers('local server timed out'); }, PROBE_TIMEOUT);

    ws.onopen = function() {
        if (settled || self.destroyed) { try { ws.close(); } catch (e) {} return; }
        settled = true;
        clearTimeout(timer);
        console.log('using local signaling server');
        self.adopt(new LocalSignal(self.identifier, ws));
    };
    ws.onerror = function() { useTrackers('no local server'); };
    ws.onclose = function() { useTrackers('local server closed'); };
};

Transport.prototype.send = function(peer, msg) {
    if (this.inner) return this.inner.send(peer, msg);
    var self = this;
    return new Promise(function(resolve, reject) {
        self.queue.push({peer: peer, msg: msg, resolve: resolve, reject: reject});
    });
};

Transport.prototype.destroy = function() {
    this.destroyed = true;
    if (this.inner && this.inner.destroy) this.inner.destroy();
};

function createTransport(identifier) {
    return new Transport(identifier);
}
